version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas"
s3_bucket = "sam-bootstrap-bucket-3229e64d-62d0-48a7-9bde-4c2e052ed6d3"
s3_prefix = "serverless-saas"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"